### ISSUE TITLE
Mod does not work with custom resource packs

### ISSUE THREAD

**Issue by fwolle30** [magneticflux-/fabric-diagonal-panes#15]
Like stated in the title, this mod does not work , if you use a resource pack like sphax pure BD Craft.

If you disable it, everything works like it should. But with Sphax Enabled, your mod does not work.

**Comment by magneticflux-** [comment]
I use Faithful 32x and it works with that. Perhaps Sphax PureBDcraft overwrites my models with their own custom glass pane block models. Could you share the exact resource pack you use?

**Comment by Gantros** [comment]
I am getting this BDcraft problem, as well, I use PureBDCraft 128x MC 1.15, as well as their More 3D Blocks, 3D Items, and Better Leaves addons, all for 1.15

**Comment by magneticflux-** [comment]
I am able to reproduce this using BDcraft. I'm working on a way to modify the load order of the changes since BDcraft overrides the changes we make to glass pane models.

![2020-04-22_14 29 27](https://user-images.githubusercontent.com/9124288/80025089-b3d87880-84a5-11ea-8b22-ba53b55241f2.png)

**Comment by magneticflux-** [comment]
I have diagonal panes working now:

![2020-04-23_17 04 12](https://user-images.githubusercontent.com/9124288/80154128-93cbb680-8584-11ea-98ba-2c8b4d7c728a.png)

 Expect a release in an hour or two.

**Comment by magneticflux-** [comment]
If you use a resource pack and use OptiFabric, you have to disable the "Optifine Internal Resources" resource pack and download your pack's custom Optifine resources because Optifine likes to load CTM textures in the wrong order. This results in the panes using the default 16x CTM textures. BDCraft's addon is [here](https://bdcraft.net/downloads/purebdcraft-minecraft/optifine-ctm-transitions/).
